spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  resources:
        static-locations: classpath:/templates
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 2000
    database: 0
    timeout: 100




